In [109]:
import time
import datetime
import pandas as pd
import requests


NOW = int(time.time() - 10000)*1000 # 현재 시간
LIMIT = 50 # 조회하는 페어데이터 갯수
SYMBOL = 'BTCUSDT' # 조회하는 페어데이터 명
INTERVAL = '15m' # 조회하는 데이터 간격
BASE_URL = 'https://www.binance.com/api/v3/uiKlines?limit={}&symbol={}&interval={}&startTime={}'.format(LIMIT, SYMBOL, INTERVAL, NOW)

get_time_stamp = int(time.time() - 60*60*24*120)*1000

df = pd.read_json(BASE_URL)

df_candle = pd.DataFrame()
print(df)

def get_date(mili_time):
    KST = datetime.timezone(datetime.timedelta(hours=9))
    dt = datetime.datetime.fromtimestamp(mili_time / 1000.0, tz = KST)
    timeline = str(dt.strftime('%D %H: %M: %S'))
    return timeline


for i in range(int(120*1.4)):
    LOOP_URL = 'https://www.binance.com/api/v3/uiKlines?limit={}&symbol={}&interval={}&startTime={}'.format(LIMIT, SYMBOL, INTERVAL, get_time_stamp)

    webpage = requests.get(LOOP_URL)
    df_candle_temp = pd.read_json(LOOP_URL)
    
    df_candle = pd.concat([df_candle, df_candle_temp], axis=0)    
    
    get_time_stamp = df_candle_temp[0][-1:].values[0]

df_candle.head()

               0         1         2         3         4           5   \
0   1673503200000  18087.54  18140.00  18085.30  18123.86  2945.51088
1   1673504100000  18124.25  18151.61  18122.03  18128.75  2251.99365
2   1673505000000  18129.36  18139.16  18108.56  18129.14  1844.92821
3   1673505900000  18128.62  18164.19  18127.37  18147.77  2099.03310
4   1673506800000  18147.25  18176.13  18140.65  18173.14  1765.07436
5   1673507700000  18173.15  18177.97  18157.54  18158.31  1554.80557
6   1673508600000  18158.31  18167.29  18117.30  18120.23  2108.85499
7   1673509500000  18120.23  18150.07  18118.06  18138.22  2447.57225
8   1673510400000  18138.21  18141.63  18071.06  18100.91  3302.18569
9   1673511300000  18100.04  18133.76  18096.18  18129.43  2245.91207
10  1673512200000  18129.42  18135.54  18102.43  18105.80  1445.60849

               6             7      8           9             10  11
0   1673504099999  5.336011e+07  69384  1557.42943  2.821306e+07   0
1   1673504999999  4.084024e+07  58443  1104.69193  2.003401e+07   0
2   1673505899999  3.343596e+07  54403   909.70616  1.648711e+07   0
3   1673506799999  3.809890e+07  50847  1017.30596  1.846480e+07   0
4   1673507699999  3.204832e+07  51292   890.05287  1.616161e+07   0
5   1673508599999  2.824457e+07  46854   745.04505  1.353474e+07   0
6   1673509499999  3.827585e+07  54611   958.81579  1.740288e+07   0
7   1673510399999  4.438161e+07  52721  1172.58034  2.126207e+07   0
8   1673511299999  5.978255e+07  75605  1587.92065  2.874700e+07   0
9   1673512199999  4.069239e+07  55479  1064.57974  1.928954e+07   0
10  1673513099999  2.619201e+07  43074   648.31076  1.174658e+07   0

,0,1,2,3,4,5,6,7,8,9,10,11
0,1663145100000,20358.07,20419.83,20352.16,20384.88,4161.66344,1663145999999,8.485407e+07,71212,2052.11030,4.184186e+07,0
1,1663146000000,20383.97,20384.90,20329.08,20344.33,3115.66896,1663146899999,6.343090e+07,56890,1485.56200,3.024492e+07,0
2,1663146900000,20345.17,20386.08,20329.65,20380.53,2764.75783,1663147799999,5.629575e+07,51427,1348.30262,2.745527e+07,0
3,1663147800000,20380.53,20405.00,20332.54,20333.00,2547.47558,1663148699999,5.187172e+07,47215,1238.93994,2.523107e+07,0
4,1663148700000,20333.00,20353.78,20311.93,20347.79,2616.76917,1663149599999,5.321022e+07,48787,1273.82528,2.590307e+07,0